"""empty message

Revision ID: 3cd09691e6de
Revises: a2d864d45176
Create Date: 2024-07-18 15:07:41.095264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd09691e6de'
down_revision = 'a2d864d45176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('racing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('shooter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shooter', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('racing', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
